version: '3.4'

networks:
  dev:
    driver: bridge
  service-proxy:
volumes:
  app:
    driver: local
  db:
    driver: local
  pgadmin:
    driver: local

services:
  # app
  app:
    # cmd for get image
    # >docker build -f SuntacAPI/Dockerfile -t sample:v1.0 .
    # cmd for run app
    # >docker run -it --rm -p 8080:80 sample:v1.0
    # build and run single service
    # docker-compose up -d --force-recreate --no-deps --build <service_name>
    image: docker.io/library/sample:v1.0
    build:
      context: .
      dockerfile: SampleAPI/Dockerfile
    container_name: sample-v1.0
    depends_on:
      - "db"
    ports:
      - "8080:80"
    environment:
      - "CONNECTION_STRING=..."
      - "ASP_NET_CORE_URL=http://+:80"
    networks:
      - dev
    volumes:
      - "./app:/app/publish" 

  # database
  db:
    image: postgres:latest
    container_name: db
    # automatically restarts the container - Docker deamon on restart network_mode: 
    # the container itself is manually restarted
    restart: always
    environment:
      - "POSTGRES_USER=root"
      - "POSTGRES_PASSWORD=@Pas5word"
      - "POSTGRES_DB=sample"
    networks:
      - default
      - service-proxy
    ports:
      - "5050:5432"
    volumes:
      - "./db/data:/var/lib/postgresql/data"

  # tool
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    environment:
      - "PGADMIN_DEFAULT_EMAIL=root@root.com"
      - "PGADMIN_DEFAULT_PASSWORD=@Pas5word"
    # PGADMIN_LISTEN_PORT = 80
    ports:
      - "5051:80"
    volumes:
      - "./db/pgadmin:/var/lib/pgadmin"